### ISSUE TITLE
可否在其他平台同步打卡楼主的进度？

### ISSUE THREAD

**Issue by Everfighting** [yuzhoujr/leetcode#7]
前几天想在微信上打卡刷Leetcode题目，今天看到楼主的计划感觉很科学。
想按照题主给出的计划同步做题打卡，不知道是否可以？

会申明计划来源，想让更多的人参与进来。

**Comment by yuzhoujr** [comment]
可以啊，所有的进程在这：
https://github.com/yuzhoujr/leetcode/projects/1

**Comment by Everfighting** [comment]
谢谢~ 后面希望能跟上楼主进度
