### ISSUE TITLE
Binary Search 总结帖 (更新完)

### ISSUE THREAD

**Issue by yuzhoujr** [yuzhoujr/leetcode#8]
####  Leetcode
> Day 1
- [x] 852	Peak Index in a Mountain Array
- [x] 349	Intersection of Two Arrays
- [x] 167	Two Sum II - Input array is sorted
- [x] 350	Intersection of Two Arrays II
- [x] 744	Find Smallest Letter Greater Than Target
---
> Day 2
- [x] 35	Search Insert Position
- [x] 278	First Bad Version
- [x] 367	Valid Perfect Square
- [x] 374	Guess Number Higher or Lower
- [x] 441	Arranging Coins
- [x] 69. Sqrt(x)
---
> Day 3 - 6
- [x] 658. Find K Closest Elements
- [x] 162. Find Peak Element
- [x] 153. Find Minimum in Rotated Sorted Array
- [x] 74. Search a 2D Matrix
- [x] 34. Search for a Range
- [x] 240. Search a 2D Matrix II
- [x] 33. Search in Rotated Sorted Array
- [x] 81. Search in Rotated Sorted Array II

####  Lintcode

> Day 3 - 5
- [x] 458. Last Position of Target
- [x] 585. Maximum Number in Mountain Sequence
- [x] 447. Search in a Big Sorted Array
- [x] 462. Total Occurrence of Target
- [x] 459. Closest Number in Sorted Array

#### 刷题先后顺序：
* 有明确Target的Easy, Medium
* 没有明确Target的Easy，Medium
    * 纳尼，你说你弄不懂到底返回`left`还是`right`，不慌，送你边界处理[神器](http://pythontutor.com/visualize.html#mode=display)
    * 该神器的使用方法：把代码拷过去，然后initiatize一个object，随便传入一个Test Case，然后点运行。代码会一步一步的跑，你就可以看你`left`和`right`在每一层迭代之后的值了。
* 没有明确Target的Easy，Medium (边界变种)

![不用谢啦](https://raw.githubusercontent.com/yuzhoujr/leetcode/master/img/binary_search.png)

**Comment by yuzhoujr** [comment]
# LeetCode Binary Search Summary 二分搜索法小结
> 资源一： http://www.cnblogs.com/grandyang/p/6854825.html
> 作者：grandyang
 
二分查找法作为一种常见的查找方法，将原本是线性时间提升到了对数时间范围，大大缩短了搜索时间，具有很大的应用场景，而在LeetCode中，要运用二分搜索法来解的题目也有很多，但是实际上二分查找法的查找目标有很多种，而且在细节写法也有一些变化。之前有网友留言希望博主能针对二分查找法的具体写法做个总结，博主由于之前一直很忙，一直拖着没写，为了树立博主言出必行的正面形象，不能再无限制的拖下去了，那么今天就来做个了断吧，总结写起来~ (以下内容均为博主自己的总结，并不权威，权当参考，欢迎各位大神们留言讨论指正)

根据查找的目标不同，博主将二分查找法主要分为以下四类：

 

## 第一类： 需查找和目标值完全相等的数

这是最简单的一类，也是我们最开始学二分查找法需要解决的问题，比如我们有数组[2, 4, 5, 6, 9]，target = 6，那么我们可以写出二分查找法的代码如下：

 

    int find(vector<int>& nums, int target) {
        int left = 0, right = nums.size();
        while (left < right) {
            int mid = left + (right - left) / 2;
            if (nums[mid] == target) return mid;
            else if (nums[mid] < target) left = mid + 1;
            else right = mid;
        }
        return -1;
    }


会返回3，也就是target的在数组中的位置。注意二分查找法的写法并不唯一，主要可以变动地方有四处：

第一处是right的初始化，可以写成 nums.size() 或者 nums.size() - 1

第二处是left和right的关系，可以写成 left < right 或者 left <= right

第三处是更新right的赋值，可以写成 right = mid 或者 right = mid - 1

第四处是最后返回值，可以返回left，right，或right - 1

但是这些不同的写法并不能随机的组合，像博主的那种写法，若right初始化为了nums.size()，那么就必须用left < right，而最后的right的赋值，用哪个都可以，博主偷懒就不写-1了。但是如果我们right初始化为 nums.size() - 1，那么就必须用 left <= right，并且right的赋值要写成 right = mid - 1，不然就会出错。所以博主的建议是选择一套自己喜欢的写法，并且记住，实在不行就带简单的例子来一步一步执行，确定正确的写法也行。

第一类应用实例：

[Intersection of Two Arrays](http://www.cnblogs.com/grandyang/p/5507129.html)

 

## 第二类： 查找第一个不小于目标值的数，可变形为查找最后一个小于目标值的数

这是比较常见的一类，因为我们要查找的目标值不一定会在数组中出现，也有可能是跟目标值相等的数在数组中并不唯一，而是有多个，那么这种情况下nums[mid] == target这条判断语句就没有必要存在。比如在数组[2, 4, 5, 6, 9]中查找数字3，就会返回数字4的位置；在数组[0, 1, 1, 1, 1]中查找数字1，就会返回第一个数字1的位置。我们可以使用如下代码：


    int find(vector<int>& nums, int target) {
        int left = 0, right = nums.size();
        while (left < right) {
            int mid = left + (right - left) / 2;
            if (nums[mid] < target) left = mid + 1;
            else right = mid;
        }
        return right;
    }

 

最后我们需要返回的位置就是right指针指向的地方。在C++的STL中有专门的查找第一个不小于目标值的数的函数lower_bound，在博主的解法中也会时不时的用到这个函数。但是如果面试的时候人家不让使用内置函数，那么我们只能老老实实写上面这段二分查找的函数。

这一类可以轻松的变形为查找最后一个小于目标值的数，怎么变呢。我们已经找到了第一个不小于目标值的数，那么再往前退一位，返回right - 1，就是最后一个小于目标值的数。

第二类应用实例：

[Heaters](http://www.cnblogs.com/grandyang/p/6181626.html)<span style="font-family: gotham, helvetica, arial, sans-serif; font-size: 14px;">，</span> [Arranging Coins](http://www.cnblogs.com/grandyang/p/6026066.html)<span style="font-family: gotham, helvetica, arial, sans-serif; font-size: 14px;">，</span> [Valid Perfect Square](http://www.cnblogs.com/grandyang/p/5619296.html)<span style="font-family: gotham, helvetica, arial, sans-serif; font-size: 14px;">，</span>[Max Sum of Rectangle No Larger Than K](http://www.cnblogs.com/grandyang/p/5617660.html)<span style="font-family: gotham, helvetica, arial, sans-serif; font-size: 14px;">，</span>[Russian Doll Envelopes](http://www.cnblogs.com/grandyang/p/5568818.html)

第二类变形应用：[Valid Triangle Number](http://www.cnblogs.com/grandyang/p/7053730.html)

 <br>
 <br>

 
## 第三类： 查找第一个大于目标值的数，可变形为查找最后一个不大于目标值的数

这一类也比较常见，尤其是查找第一个大于目标值的数，在C++的STL也有专门的函数upper_bound，这里跟上面的那种情况的写法上很相似，只需要添加一个等号，将之前的 nums[mid] < target 变成 nums[mid] <= target，就这一个小小的变化，其实直接就改变了搜索的方向，使得在数组中有很多跟目标值相同的数字存在的情况下，返回最后一个相同的数字的下一个位置。比如在数组[2, 4, 5, 6, 9]中查找数字3，还是返回数字4的位置，这跟上面那查找方式返回的结果相同，因为数字4在此数组中既是第一个不小于目标值3的数，也是第一个大于目标值3的数，所以make sense；在数组[0, 1, 1, 1, 1]中查找数字1，就会返回坐标5，通过对比返回的坐标和数组的长度，我们就知道是否存在这样一个大于目标值的数。参见下面的代码：

 
    int find(vector<int>& nums, int target) {
        int left = 0, right = nums.size();
        while (left < right) {
            int mid = left + (right - left) / 2;
            if (nums[mid] <= target) left = mid + 1;
            else right = mid;
        }
        return right;
    }
 

这一类可以轻松的变形为查找最后一个不大于目标值的数，怎么变呢。我们已经找到了第一个大于目标值的数，那么再往前退一位，返回right - 1，就是最后一个不大于目标值的数。比如在数组[0, 1, 1, 1, 1]中查找数字1，就会返回最后一个数字1的位置4，这在有些情况下是需要这么做的。

第三类应用实例：

[Kth Smallest Element in a Sorted Matrix](http://www.cnblogs.com/grandyang/p/5727892.html)

第三类变形应用示例：

[Sqrt(x)](http://www.cnblogs.com/grandyang/p/4346413.html)

 

##第四类： 用子函数当作判断关系

这是最令博主头疼的一类，而且通常情况下都很难。因为这里在二分查找法重要的比较大小的地方使用到了子函数，并不是之前三类中简单的数字大小的比较，比如Split Array Largest Sum那道题中的解法一，就是根据是否能分割数组来确定下一步搜索的范围。类似的还有Guess Number Higher or Lower这道题，是根据给定函数guess的返回值情况来确定搜索的范围。对于这类题目，博主也很无奈，遇到了只能自求多福了。

第四类应用实例：

[Split Array Largest Sum](http://www.cnblogs.com/grandyang/p/5933787.html)， [Guess Number Higher or Lower](http://www.cnblogs.com/grandyang/p/5666502.html)，[Find K Closest Elements](http://www.cnblogs.com/grandyang/p/7519466.html)，[Find K-th Smallest Pair Distance](http://www.cnblogs.com/grandyang/p/8627783.html)，[Kth Smallest Number in Multiplication Table](http://www.cnblogs.com/grandyang/p/8367505.html)，[Maximum Average Subarray II](http://www.cnblogs.com/grandyang/p/8021421.html)，[Minimize Max Distance to Gas Station](http://www.cnblogs.com/grandyang/p/8970057.html)，[Swim in Rising Water](http://www.cnblogs.com/grandyang/p/9017300.html)

 

综上所述，博主大致将二分搜索法的应用场景分成了主要这四类，其中第二类和第三类还有各自的扩展。根据目前博主的经验来看，第二类和第三类的应用场景最多，也是最重要的两类。第一类和第四类较少，其中第一类最简单，第四类最难，遇到这类，博主也没啥好建议，多多练习吧～

 

如果有写的有遗漏或者错误的地方，请大家踊跃留言啊，共同进步哈～

 

LeetCode All in One 题目讲解汇总(持续更新中...)

**Comment by yuzhoujr** [comment]
# 公瑾总结

本总结参考制了很多综合帖的内容，全部参考文档会赋予文章底部。

## Binary Search | 二分查找法
> 用途：**针对Sorted数组查找的算法**
> 时间复杂度: O(log(n))

当面对一个Sorted数组 `arr`，并要求查找一个`target`数值时候。

* 对数组切半，中间值`mid`用于判断下列三种情况
     * 如果定义的`arr[mid]`刚好等于要查找`target`，返回
     * 如果定义的`arr[mid]`比`target`值要大，说明target值只能出现在mid的左边，舍弃右边一半的数组
     * 如果定义的`arr[mid]`比`target`值要小，说明target值只能出现在mid的右边，舍弃左边一半的数组
* 重复上面3种情况，直到找到为止。

<br><br>
## 代码实现
### Iterative
**Binary Search基础实现1，包括End区间，end inclusive**
```
def binarySearch(arr, target):
    '''
    定义：在[l...r]的范围里寻找target, 因为这里定义是需要将r归入范围区间, inclusive，所以while循环的边界需要包含r
    '''
    l , r = 0, len(arr) - 1  
    while l <= r:            

        mid = (l+r)//2
        if arr[mid] == target:
            return mid
        if target > arr[mid]:
            l = mid + 1   # 明确区间的要求，只要使用过的，一律绕过。
        else:
            r = mid - 1   # 明确区间的要求，只要使用过的，一律绕过。
    return -1
            
```

**Binary Search基础实现2，不包括End区间, end exclusive**
```
def binarySearch(arr, target):
    '''
    定义：在[l...r)的范围里寻找target, 因为这里定义是不需要将end归入范围区间
    exclusive，所以while循环的边界小于End即可，因为length本身长度会比index大1
    相对应的，每次target的value小于arr[mid]的时候，我们在重新定义新的end时候，
    也选择exclusive的模式，r = mid即可
    '''
    l , r = 0, len(arr)
    while l < r:            
        mid = (l+r)//2
        if arr[mid] == target:
            return mid
        if target > arr[mid]:
            l = mid + 1  
        else:
            r = mid
    return -1
            
```

**上述代码仍可能产生溢出的Bug，下面方法为无Bug的标准写法**

溢出bug的解释: When you add two signed 32-bit integers, you always run the risk of overflow. You can try it yourself with low = 1 and high = Integer.MAX_VALUE. You'll notice however that the second way stops this overflow from occurring, and you get your expected result.
```
def binarySearch(arr, target):
    '''
    针对mid加法溢出bug的解决方案：将(l+r)/2 变成 l + (r-l)/2 来避免加法之后的除法
    '''
    l , r = 0, len(arr) - 1  
    while l <= r:            

        mid = l + (r - l) // 2
        if arr[mid] == target:
            return mid
        if target > arr[mid]:
            l = mid + 1   # 明确区间的要求，只要使用过的，一律绕过。
        else:
            r = mid - 1   # 明确区间的要求，只要使用过的，一律绕过。
    return -1
```
### Recursive
```
class Solution:
    def findPosition(self, nums, target):
        return self.binarySearch(nums, 0, len(nums) - 1, target)
    
    def binarySearch(self, nums, start, end, target):
        if start > end: 
            return -1
        mid = start + (end - start)// 2
        if nums[mid] == target:
            return mid
        if nums[mid] < target:
            return self.binarySearch(nums, mid+1, end, target)
        else:
            return self.binarySearch(nums, start, mid-1 , target)
```

**Comment by gengwuli** [comment]
愚见: 首先是关于左闭右闭，合左闭右开。楼主对每一种情况分析的都很细致，但是实际操作起来往往需要统一口径，持续使用一种稳定的算法。这样实战的时候就不会被各种情况所干扰。个人认为左闭右闭更加直接，因为这样考虑左边界右边界都是同样的思路(l = m + 1, r = m - 1)。
然后就是+1和-1的问题，到底是+1还是-1，除了跟判断条件有关，还跟mid的计算有关。 mid = l + (r - l) / 2. 这里(r - l) / 2可能会省略额外的0.5导致mid会偏向左边。 如果r和l足够大，这不是事。 但是如果l + 1 = r也就是二者相邻的时候，这是(r -  l) / 2 = 1 / 2 = 0.5 导致mid=l。 所以起码要保证赋值中不能出现l = mid。 仔细分析852这道题可以理解。
最后就是判断条件，到底是l < r, l <= r, 还是l + 1 < r？ 如果是l < r跳出循环后l = r, 如果l <= r出来l + 1 = r， 如果l + 1 < r的话, 那么出来就是l + 1 = r. 前两种条件都会出现循环内l + 1 = r的情况，所以需要留意mid=l。 第三种情况(l + 1 = r) ，因为只剩下两个，所以我们只需要再做一次判断就可以了。

综上所述，总结除了模板。 
`scala
def search(arr:Array[Int], target: Int): Int = {
  var (l, r) = (0, arr.length - 1)
  while (l + 1 < r) {
    val m = l + (r - l) / 2
    if (arr(m) == target) {
      return m
    }
    if (arr(m) < target) {
      l = m
    } else {
      r = m
    }
  }
  if (arr(l) == target) { return l }
  if (arr(r) == target) { return r }
  return -1
}
`
首先判断条件总是l + 1 < r， 不用担心mid = l 循环的情况。然后l = mid, r = mid, 不用担心+1-1的情况。
出来只需要多一次判断左边和右边位置的数就可以了。非常稳定。 

最后我们可能需要考虑，如果有重复元素怎么办，重复元素找左右边界。 
还有一些题目本身不像二分查找，但是怎么转化为二分问题。

**Comment by yuzhoujr** [comment]
@gengwuli 嗯嗯，我还在整理，我现在用的是左闭右闭刷的，你说的没错，我之后会在总结帖里面加上你的提醒。然后我现在还在整理关于边界返回的问题，比如sqrt(x)这题，我看了一个知乎的回答，[链接](https://www.zhihu.com/question/36132386/answer/155438728)，目前还是没有搞懂他说的永远返回Low这点，因为我sqrt(x)返回的是right，总而言之，我目前对边界的概念还处在摸索阶段，有些模糊

**Comment by yuzhoujr** [comment]
@gengwuli ，这是我sqrt(x)的代码：
```
class Solution(object):
    def mySqrt(self, n):
        """
        :type x: int
        :rtype: int
        """
        l, r = 0 , n
        while l <= r:
            mid = l + (r-l)//2
            if mid * mid == n:
                return mid
            if mid * mid < n:
                l = mid + 1
            else:
                r = mid - 1
        return r
```

这是知乎作者的代码:
```
public class Solution {
    public int mySqrt(int x) {
        if (x <= 0) { return 0; }
        int lo = 1, hi = x;
        while (lo < hi) {
            int mid = lo + ( (hi - lo + 1) / 2 ); // 注意！取上位中位数
            long product = (long)mid * mid;
            if (product > (long)x) {
                hi = mid - 1;
            } else if (product < (long)x) {
                lo = mid;
            } else { // product == x
                return mid;
            }
        }
        return lo;
    }
}
```

**Comment by gengwuli** [comment]
我的是这样的，比较好理解一点，同样是用的模板。 
```java
public class Solution {
    public int mySqrt(int x) {
        if (x < 0) {
            throw new RuntimeException("Error!");
        }
        int start = 0, end = x;
        while (start + 1 < end) {
            int mid = start + (end - start) / 2;
            if (mid == x / mid) {
                return mid;
            }
            if ((long) mid * mid < x) {
                start = mid;
            } else {
                end = mid;
            }
        }
        if ((long) end * end == x) {
            return end;
        }
        return start;
    }
}
```
唯一不同的就是最后先看end * end == x。 回头我再仔细看看你这种解法。 
不过我觉得有必要总结一下题型频率。 感觉二分考的不是很多。花多少时间在上面是个问题。

**Comment by Duan-JM** [comment]
太帅了，谢谢大佬呀～

**Comment by cc776** [comment]
总结特别到位 👍

**Comment by xiedaxia1hao** [comment]
Thanks!

**Comment by ShangxuanWu** [comment]
赞！

**Comment by l0latgithub** [comment]
LC658 如何用某章的模板解决哪？新手问题，见谅！

**Comment by shiywang** [comment]
总结的很好，很适合新手，下面是进阶帖: [写对二分查找不能靠模板，需要理解加练习 （附练习题，持续更新）](https://leetcode-cn.com/problems/search-insert-position/solution/te-bie-hao-yong-de-er-fen-cha-fa-fa-mo-ban-python-/)

**Comment by BWJerry** [comment]
非常漂亮的總結，想詢問
痛点2.5 : 死循环
上面的情况还只是把边界的其中一个写错, 也就是右边的边界值写错, 如果两者同时都写错的话, 可能会造成死循环, 比如下面的这个程序:

    l , r = 0, len(arr) - 1
    while l <= r:            
        mid = l + (r-l)//2
        if arr[mid] == target:
            return mid
        if target > arr[mid]:
            l = mid
        else:
            r = mid
    return -1
这个程序采用的是左闭右闭的区间. 但是,
当 target < arr[mid] 的时候, 那么下一次查找的区间应该为 **[mid + 1, right]**, 
当 target > arr[mid] 的时候, 那么下一次查找的区间应该为 **[left, mid - 1]**, 
這兩個文字說明的下一次查找的区间是否寫反了謝謝！
